# Generated by Django 4.0 on 2022-02-19 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpayment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.shoppingsession'),
        ),
    ]
