# Generated by Django 4.0 on 2022-02-28 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcounty',
            name='county',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcounty_county', to='shops.county'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='name',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AlterField(
            model_name='ward',
            name='subcounty',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcounty_ward', to='shops.subcounty'),
        ),
    ]
