# Generated by Django 4.0 on 2022-02-24 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=40)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.county')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='registration_id',
            field=models.CharField(default=None, max_length=69, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='county',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='county', to='shops.shopkeeper'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopkeeper',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shopkeepers', to='shops.shopkeeper'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=30)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.subcounty')),
            ],
        ),
    ]
