# Generated by Django 4.0 on 2021-12-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
