# Generated by Django 4.0 on 2021-12-26 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_productcategory_shopproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='start_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
        ),
    ]
