# Generated by Django 4.0 on 2021-12-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_invoice_shoppingsession_orderitem_invoice_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='p_description',
            field=models.TextField(max_length=500),
        ),
    ]
