# Generated by Django 4.0 on 2022-02-28 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shopkeeper_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='county',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='county', to='shops.county'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='subcounty',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='subcounty', to='shops.subcounty'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='ward',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ward', to='shops.ward'),
        ),
    ]
