# Generated by Django 4.0 on 2021-12-31 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_productcategory_p_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingsession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
