# Generated by Django 4.0 on 2022-03-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shop_county_alter_shop_subcounty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopkeeper',
            name='national_id',
        ),
        migrations.AddField(
            model_name='shop',
            name='confirmation_code',
            field=models.CharField(default='TR23', max_length=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='device_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='identity_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
