# Generated by Django 4.0 on 2021-12-31 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_shoppingsession_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='session',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shoppingsession'),
        ),
    ]
