# Generated by Django 4.0 on 2021-12-26 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_rename_prediction_shopproduct_p_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.productcategory'),
        ),
    ]
