# Generated by Django 4.0 on 2021-12-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_cartitem_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingsession',
            name='total',
            field=models.BigIntegerField(blank=True),
        ),
    ]
