# Generated by Django 4.0 on 2022-03-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_otpauthentication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpauthentication',
            name='phone_number',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
