# Generated by Django 4.0 on 2022-03-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_alter_otpauthentication_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopkeeper',
            name='is_employee',
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
