# Generated by Django 4.0 on 2021-12-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_alter_shoppingsession_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingsession',
            name='total',
            field=models.BigIntegerField(null=True),
        ),
    ]
