# Generated by Django 4.0 on 2022-02-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shop_password'),
        ('shops', '0007_alter_shoppingsession_total'),
    ]

    operations = [
    ]
