# Generated by Django 4.0 on 2022-03-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_remove_shopkeeper_is_employee_shopkeeper_is_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopkeeper',
            name='firebase_token',
        ),
    ]
