# Generated by Django 4.0 on 2022-02-09 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_creditpayment_paymentmethod'),
        ('shops', '0008_merge_20220209_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingsession',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='payment.paymentmethod'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='minimum_stock_level',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='reorder_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='mode_of_payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='payment', to='payment.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
