# Generated by Django 4.0 on 2022-03-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_remove_shopkeeper_firebase_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopkeeper',
            name='device_id',
        ),
        migrations.AddField(
            model_name='shop',
            name='device_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
