# Generated by Django 4.0 on 2022-03-16 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_remove_shopkeeper_device_id_shop_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='shop',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shops.shop'),
        ),
    ]
