# Generated by Django 4.0 on 2022-02-13 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_creditpayment_date_payment_expected_and_more'),
        ('shops', '0010_alter_shoppingsession_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingsession',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='payment.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
